require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'

target 'GenesisApp' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true
  )

  post_install do |installer|
    react_native_post_install(installer)

    targets = installer.pods_project.targets + installer.aggregate_targets.flat_map { |t| t.user_project.native_targets }

    targets.each do |target|
      target.build_configurations.each do |config|
        %w[OTHER_CFLAGS OTHER_CPLUSPLUSFLAGS OTHER_LDFLAGS].each do |flag|
          value = config.build_settings[flag]
          next if value.nil?

          cleaned = false
          if value.is_a?(Array)
            new_val = value.reject { |f| f == '-G' }
            cleaned = new_val.length != value.length
            config.build_settings[flag] = new_val
          elsif value.is_a?(String)
            new_val = value.gsub(/(\s)-G(\s|$)/, '\1\2').squeeze(' ').strip
            cleaned = new_val != value
            config.build_settings[flag] = new_val
          end

          puts "Removed -G from #{target.name} #{config.name} #{flag}" if cleaned
        end
      end
    end

    system('node', File.join(__dir__, '..', 'scripts', 'stripDashG.js'))
  end
end
